---
- name: Install Docker and Docker Compose on AlmaLinux 8
  hosts: odoo-server
  become: true
  tasks:
    - name: Update and upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install necessary packages
      ansible.builtin.dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'

    - name: Install Docker
      ansible.builtin.dnf:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      ansible.builtin.command: docker-compose --version
      register: docker_compose_version
      changed_when: false

    - name: Display Docker Compose version
      ansible.builtin.debug:
        msg: "Docker Compose version installed: {{ docker_compose_version.stdout }}"

    - name: Add odoo user to docker group
      ansible.builtin.user:
        name: odoo
        groups: docker
        append: true

    - name: Create Docker network using command module
      ansible.builtin.command:
        cmd: docker network create odoo-network
      register: result
      failed_when: result.rc != 0 and 'already exists' not in result.stderr
      changed_when: '"already exists" not in result.stderr'
