version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: odoo_pg16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: EIZEVcCQwlNmVeg
    volumes:
      - /home/odoo/odoo_prod/pg/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - odoo-network

networks:
  odoo-network:
    external: true
